name: fetch_link_data
description: Fetch all URL data such as title , description , image , video ... etc . and it's written in pure dart so you can use it any where you need ^_^
version: 1.0.1
repository: https://github.com/Mohamed-Nagdy/fetch_link_data

environment:
  sdk: ^3.0.1

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0
  http: ^1.1.0
  html: ^0.15.4

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
