name: fetch_link_data
description: Fetch All URLs Metadata Anytime Any Website
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.0.1

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0
  http: ^1.1.0
  html: ^0.15.4

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
